let gameGenreArr = [] ; //649種類のジャンル
gameGenreArr.push("ハックアンドスラッシュ,アクションアドベンチャーゲーム" );
gameGenreArr.push("リズムゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム" );
gameGenreArr.push("スポーツゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("コンピュータRPG" );
gameGenreArr.push("プラットフォーム・ゲーム" );
gameGenreArr.push("アクションゲーム,迷路ゲーム" );
gameGenreArr.push("アクションゲーム" );
gameGenreArr.push("ターン制ストラテジー" );
gameGenreArr.push("対戦格闘ゲーム,クロスオーバー作品" );
gameGenreArr.push("対戦格闘ゲーム" );
gameGenreArr.push("レースゲーム" );
gameGenreArr.push("恋愛映画" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,リアルタイムタクティクス" );
gameGenreArr.push("シミュレーションロールプレイングゲーム" );
gameGenreArr.push("アドベンチャーゲーム" );
gameGenreArr.push("アクションゲーム,プラットフォーム・ゲーム" );
gameGenreArr.push("サバイバルホラー" );
gameGenreArr.push("リアルタイムストラテジー" );
gameGenreArr.push("3次元コンピュータグラフィックス" );
gameGenreArr.push("snowboarding video game" );
gameGenreArr.push("スポーツ" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,シューティングゲーム" );
gameGenreArr.push("アクションゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("音楽ゲーム" );
gameGenreArr.push("アクションゲーム,シューティングゲーム" );
gameGenreArr.push("スポーツゲーム,プロレス" );
gameGenreArr.push("シューティングゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("アドベンチャーゲーム,DVDプレイヤーズゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,サバイバルホラー" );
gameGenreArr.push("レースシミュレーション" );
gameGenreArr.push("アクションロールプレイングゲーム" );
gameGenreArr.push("アクションゲーム,B級映画" );
gameGenreArr.push("プラットフォーム・ゲーム,対戦格闘ゲーム" );
gameGenreArr.push("パズルゲーム,ストラテジーゲーム" );
gameGenreArr.push("乙女ゲーム" );
gameGenreArr.push("シューティングゲーム,フライトシミュレーション" );
gameGenreArr.push("ストラテジーゲーム" );
gameGenreArr.push("シミュレーションゲーム" );
gameGenreArr.push("surfing video game" );
gameGenreArr.push("対戦格闘ゲーム,パーティーゲーム" );
gameGenreArr.push("ビジュアルノベル" );
gameGenreArr.push("シューティングゲーム" );
gameGenreArr.push("グラフィックアドベンチャーゲーム" );
gameGenreArr.push("basketball video game" );
gameGenreArr.push("スポーツゲーム,バスケットボール" );
gameGenreArr.push("アドベンチャーゲーム,ビジュアルノベル" );
gameGenreArr.push("車両戦闘ゲーム" );
gameGenreArr.push("パズルゲーム" );
gameGenreArr.push("golf video game" );
gameGenreArr.push("ダンス" );
gameGenreArr.push("DVDプレイヤーズゲーム" );
gameGenreArr.push("boxing video game" );
gameGenreArr.push("コンピュータRPG,オープンワールド" );
gameGenreArr.push("漁" );
gameGenreArr.push("人生シミュレーションゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ハックアンドスラッシュ" );
gameGenreArr.push("レースゲーム,オープンワールド" );
gameGenreArr.push("パズルゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,アクションロールプレイングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ステルスゲーム" );
gameGenreArr.push("パズルゲーム,ストラテジーゲーム,アクションゲーム" );
gameGenreArr.push("アクションゲーム,車両戦闘ゲーム" );
gameGenreArr.push("side-scrolling video game,アクションゲーム" );
gameGenreArr.push("恋愛,ドラマ,ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("対戦格闘ゲーム,プロレス" );
gameGenreArr.push("サイエンス・フィクション" );
gameGenreArr.push("恋愛ゲーム" );
gameGenreArr.push("恋愛映画,ビジュアルノベル" );
gameGenreArr.push("ファンタジー,アドベンチャー,ビジュアルノベル,ハーレム系,ロボットもの,アダルトゲーム" );
gameGenreArr.push("ファンタジー,ホラー,ビジュアルノベル,少年漫画" );
gameGenreArr.push("social simulation game" );
gameGenreArr.push("ドラマ,ビジュアルノベル,少年漫画,長編小説" );
gameGenreArr.push("ポップ・ミュージック,コンピュータRPG" );
gameGenreArr.push("コンピュータRPG,アクションアドベンチャーゲーム" );
gameGenreArr.push("ミニゲーム" );
gameGenreArr.push("ヘンタイ,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("ヘンタイ,ビジュアルノベル,アダルトゲーム,美少女ゲーム" );
gameGenreArr.push("コメディ,青年漫画,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("エデュテインメント" );
gameGenreArr.push("パズルゲーム,プラットフォーム・ゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,プラットフォーム・ゲーム" );
gameGenreArr.push("コンピュータRPG,アドベンチャーゲーム" );
gameGenreArr.push("学園もの,エッチ,恋愛,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("インスタントメッセージ" );
gameGenreArr.push("パズルゲーム,クロスオーバー作品,アニメ" );
gameGenreArr.push("冒険" );
gameGenreArr.push("コメディ,エッチ,ドラマ,ファンタジー,ビジュアルノベル,青年漫画,アダルトゲーム" );
gameGenreArr.push("ヘンタイ,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("アクションゲーム,パズルゲーム" );
gameGenreArr.push("ヘンタイ" );
gameGenreArr.push("クイズ" );
gameGenreArr.push("アクション,ハーレム系,魔法少女もの" );
gameGenreArr.push("ドラマ,アクション,ハーレム系,ロボットもの" );
gameGenreArr.push("メトロイドヴァニア" );
gameGenreArr.push("プラットフォーム・ゲーム,city-building game,アクションゲーム,ゴッドゲーム" );
gameGenreArr.push("ストラテジーゲーム,ターン制ストラテジー" );
gameGenreArr.push("学園もの,ハーレム系,青年漫画,少年漫画" );
gameGenreArr.push("Breakout clone" );
gameGenreArr.push("恋愛,ファンタジー,少女漫画" );
gameGenreArr.push("アクションアドベンチャーゲーム,プラットフォーム・ゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("車両戦闘ゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("シミュレーションゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("ロールプレイングゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,オープンワールド" );
gameGenreArr.push("スペースフライトシミュレーター" );
gameGenreArr.push("ミニスケープ" );
gameGenreArr.push("フライトシミュレーション" );
gameGenreArr.push("経営シミュレーションゲーム" );
gameGenreArr.push("ピンボール" );
gameGenreArr.push("run and gun" );
gameGenreArr.push("ベルトスクロールアクションゲーム" );
gameGenreArr.push("プロレス,対戦格闘ゲーム" );
gameGenreArr.push("サイコロジカルホラー" );
gameGenreArr.push("サバイバルホラー,ステルスゲーム" );
gameGenreArr.push("アクションゲーム,side-scrolling video game,プラットフォーム・ゲーム" );
gameGenreArr.push("combat flight simulator" );
gameGenreArr.push("アクションゲーム,シミュレーションゲーム" );
gameGenreArr.push("アーケードゲーム" );
gameGenreArr.push("恋愛ゲーム,ストラテジーゲーム" );
gameGenreArr.push("音楽ゲーム,シューティングゲーム" );
gameGenreArr.push("プロレス" );
gameGenreArr.push("音楽ゲーム,対戦格闘ゲーム" );
gameGenreArr.push("プラットフォーム・ゲーム,オープンワールド" );
gameGenreArr.push("educational game" );
gameGenreArr.push("SF漫画" );
gameGenreArr.push("対戦格闘ゲーム,ロボットもの" );
gameGenreArr.push("アクションゲーム,ロボットもの" );
gameGenreArr.push("アクションゲーム,シューティングゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("ベルトスクロールアクションゲーム,ハックアンドスラッシュ,アクションロールプレイングゲーム" );
gameGenreArr.push("ファンタジー" );
gameGenreArr.push("スポーツゲーム,コンピュータRPG" );
gameGenreArr.push("アクションロールプレイングゲーム,クロスオーバー作品,コンピュータRPG" );
gameGenreArr.push("アクションロールプレイングゲーム,コンピュータRPG" );
gameGenreArr.push("パーティゲーム" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,ファンタジーゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("学園もの,恋愛,ビジュアルノベル,ハーレム系,アダルトゲーム" );
gameGenreArr.push("プラットフォーム・ゲーム,アクションゲーム" );
gameGenreArr.push("メトロイドヴァニア,オープンワールド" );
gameGenreArr.push("コメディ,ファンタジー,SF漫画,アドベンチャー" );
gameGenreArr.push("SF漫画,アドベンチャー" );
gameGenreArr.push("レースゲーム,クロスオーバー作品" );
gameGenreArr.push("リアルタイムストラテジー,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("match-three video game" );
gameGenreArr.push("ライトガン,シューティングゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("アドベンチャーゲーム,パズルゲーム" );
gameGenreArr.push("タクティカルシューター" );
gameGenreArr.push("サードパーソン・シューティングゲーム,車両戦闘ゲーム" );
gameGenreArr.push("恋愛ゲーム,シミュレーションロールプレイングゲーム" );
gameGenreArr.push("ハーレム系,シミュレーションロールプレイングゲーム,恋愛ゲーム,アクションロールプレイングゲーム" );
gameGenreArr.push("アクションゲーム,クロスオーバー作品,迷路ゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,アクションロールプレイングゲーム" );
gameGenreArr.push("city-building game,ソフトウェア・トイ" );
gameGenreArr.push("city-building game" );
gameGenreArr.push("プラットフォーム・ゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ターン制ストラテジー,4X" );
gameGenreArr.push("バーチャルペット" );
gameGenreArr.push("ターン制ストラテジー,リアルタイムタクティクス" );
gameGenreArr.push("サードパーソン・シューティングゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ボードゲーム" );
gameGenreArr.push("puzzle/jigsaw video game" );
gameGenreArr.push("対戦格闘ゲーム,ロールプレイングゲーム" );
gameGenreArr.push("コンピュータRPG,サイコロジカルホラー" );
gameGenreArr.push("rail shooter" );
gameGenreArr.push("アドベンチャーゲーム,シューティングゲーム" );
gameGenreArr.push("コンピュータRPG,クロスオーバー作品,スーパーヒーローもの" );
gameGenreArr.push("プラットフォーム・ゲーム,コンピュータRPG" );
gameGenreArr.push("プラットフォーム・ゲーム,レベル・エディタ,side-scrolling video game" );
gameGenreArr.push("メトロイドヴァニア,シューティングゲーム,アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("コンピュータRPG,SFゲーム,スーパーヒーローもの" );
gameGenreArr.push("ベルトスクロールアクションゲーム,プラットフォーム・ゲーム,パズルゲーム" );
gameGenreArr.push("ドラマ,恋愛" );
gameGenreArr.push("アクションアドベンチャーゲーム,オープンワールド,ロールプレイングゲーム" );
gameGenreArr.push("Action-adventure" );
gameGenreArr.push("シューティングゲーム,side-scrolling video game" );
gameGenreArr.push("パーティーゲーム" );
gameGenreArr.push("パズルゲーム,クロスオーバー作品" );
gameGenreArr.push("ベルトスクロールアクションゲーム,シューティングゲーム" );
gameGenreArr.push("インタラクティブフィクション" );
gameGenreArr.push("ガンシューティングゲーム" );
gameGenreArr.push("ベルトスクロールアクションゲーム,オープンワールド" );
gameGenreArr.push("アクションロールプレイングゲーム,ハックアンドスラッシュ,コンピュータRPG" );
gameGenreArr.push("アクション,コンピュータRPG" );
gameGenreArr.push("レースゲーム,車両戦闘ゲーム" );
gameGenreArr.push("アクションゲーム,クロスオーバー作品" );
gameGenreArr.push("コンピュータRPG,ファンタジーゲーム" );
gameGenreArr.push("落ち物パズル" );
gameGenreArr.push("アクションロールプレイングゲーム,対戦格闘ゲーム,クロスオーバー作品,コンピュータRPG" );
gameGenreArr.push("オープンワールド,サバイバルホラー" );
gameGenreArr.push("サバイバルホラー,オープンワールド" );
gameGenreArr.push("スポーツゲーム,カジノゲーム" );
gameGenreArr.push("ピンボール,シミュレーションゲーム" );
gameGenreArr.push("迷路ゲーム" );
gameGenreArr.push("ドラマ,恋愛,アクション,ビジュアルノベル,少年漫画,長編小説" );
gameGenreArr.push("経営シミュレーションゲーム,ストラテジーゲーム" );
gameGenreArr.push("クロスオーバー作品" );
gameGenreArr.push("コンピュータRPG,ローグライクゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,ローグライクゲーム" );
gameGenreArr.push("MMORPG" );
gameGenreArr.push("コンピュータRPG,ヘンタイ,ファンタジー,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("リアルタイムストラテジー,リアルタイムタクティクス" );
gameGenreArr.push("アクションロールプレイングゲーム,combat flight simulator" );
gameGenreArr.push("video game compilation" );
gameGenreArr.push("レースゲーム,アーケードゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,サバイバルホラー" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,サバイバルホラー" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,タクティカルシューター" );
gameGenreArr.push("ロマンチック・ラブ,ビジュアルノベル" );
gameGenreArr.push("リアルタイムタクティクス" );
gameGenreArr.push("リアルタイムタクティクス,シミュレーションロールプレイングゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,タクティカルシューター" );
gameGenreArr.push("ストラテジーゲーム,クロスオーバー作品" );
gameGenreArr.push("ダンジョンアドベンチャー,コンピュータRPG" );
gameGenreArr.push("対戦格闘ゲーム,アーケードゲーム" );
gameGenreArr.push("アマチュアフライトシミュレーション" );
gameGenreArr.push("parlour game" );
gameGenreArr.push("アリーナ" );
gameGenreArr.push("Eastern role-playing game" );
gameGenreArr.push("tank simulation game" );
gameGenreArr.push("コメディドラマ,青年漫画" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,コンピュータRPG" );
gameGenreArr.push("MMORPG,コンピュータRPG" );
gameGenreArr.push("オープンワールド,アクションロールプレイングゲーム" );
gameGenreArr.push("対戦格闘ゲーム,スポーツゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,クロスオーバー作品" );
gameGenreArr.push("音楽ゲーム,exergaming" );
gameGenreArr.push("対戦格闘ゲーム,ハックアンドスラッシュ,アクションゲーム" );
gameGenreArr.push("メトロイドヴァニア,プラットフォーム・ゲーム,パズルゲーム,サイエンス・フィクション,アクションゲーム" );
gameGenreArr.push("少女漫画" );
gameGenreArr.push("ロボットもの" );
gameGenreArr.push("学園もの,ドラマ,アクション,青年漫画,少年漫画" );
gameGenreArr.push("アクションアドベンチャーゲーム,サバイバルホラー" );
gameGenreArr.push("アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("ファンタジー小説" );
gameGenreArr.push("コンピュータRPG,ストラテジーゲーム" );
gameGenreArr.push("ストラテジーゲーム,迷路ゲーム" );
gameGenreArr.push("ミニゲーム,迷路ゲーム" );
gameGenreArr.push("レースゲーム,迷路ゲーム" );
gameGenreArr.push("トレーディングカードゲーム" );
gameGenreArr.push("list of artificial pet games,パズルゲーム,シミュレーションゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,コンピュータRPG,アクションアドベンチャーゲーム,アクションゲーム" );
gameGenreArr.push("ローグライクゲーム" );
gameGenreArr.push("ゴッドゲーム" );
gameGenreArr.push("ソフトウェア・トイ" );
gameGenreArr.push("車両戦闘ゲーム,アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("サードパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("video game art,ソフトウェア・トイ" );
gameGenreArr.push("プラットフォーム・ゲーム,パズルゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,アドベンチャーゲーム,コンピュータRPG" );
gameGenreArr.push("オープンワールド,ミステリー" );
gameGenreArr.push("ステルスゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ステルスゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ステルスゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("コメディ,SF漫画,アドベンチャー" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,メトロイドヴァニア,オープンワールド" );
gameGenreArr.push("1人称視点 (ビデオゲーム),ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("美少女ゲーム,ビジュアルノベル" );
gameGenreArr.push("アドベンチャーゲーム,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("roll-and-move" );
gameGenreArr.push("アクションロールプレイングゲーム,ターン制ストラテジー" );
gameGenreArr.push("メトロイドヴァニア,プラットフォーム・ゲーム" );
gameGenreArr.push("サバイバルホラー,コンピュータRPG" );
gameGenreArr.push("ストラテジーゲーム,パズルゲーム" );
gameGenreArr.push("turns, rounds and time-keeping systems in games" );
gameGenreArr.push("audio game" );
gameGenreArr.push("コメディ,ファンタジー,少女漫画,魔法少女もの" );
gameGenreArr.push("アドベンチャーゲーム,ビジュアルノベル,クロスオーバー作品" );
gameGenreArr.push("タクティカルシューター,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("アクション,ファンタジー" );
gameGenreArr.push("ターン制ストラテジー,turn-based tactics" );
gameGenreArr.push("プラットフォーム・ゲーム,クロスオーバー作品" );
gameGenreArr.push("メトロイドヴァニア,アクションアドベンチャーゲーム" );
gameGenreArr.push("association football video game" );
gameGenreArr.push("コンピュータRPG,ファンタジー" );
gameGenreArr.push("対戦格闘ゲーム,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("リアルタイムストラテジー,トレーディングカードゲーム,リアルタイムタクティクス" );
gameGenreArr.push("グランドストラテジー" );
gameGenreArr.push("ハックアンドスラッシュ,対戦格闘ゲーム" );
gameGenreArr.push("ドラマ,ハーレム系" );
gameGenreArr.push("学園もの,百合,ビジュアルノベル,ハーレム系,青年漫画,少年漫画,アダルトゲーム" );
gameGenreArr.push("リアルタイムストラテジー,ゴッドゲーム" );
gameGenreArr.push("恋愛小説,ビジュアルノベル" );
gameGenreArr.push("アクションゲーム,リアルタイムストラテジー" );
gameGenreArr.push("喜劇,ビジュアルノベル,ハーレム系" );
gameGenreArr.push("学園もの,ドラマ,恋愛,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,アドベンチャーゲーム" );
gameGenreArr.push("アクションゲーム,アドベンチャーゲーム" );
gameGenreArr.push("ハックアンドスラッシュ,プラットフォーム・ゲーム" );
gameGenreArr.push("アクションゲーム,コンピュータRPG,オープンワールド" );
gameGenreArr.push("学園もの,ドラマ,やおい,ビジュアルノベル,少女漫画,青年漫画" );
gameGenreArr.push("少年漫画" );
gameGenreArr.push("ファンタジー映画" );
gameGenreArr.push("学園もの,やおい,少女漫画,ビジュアルノベル,青年漫画,長編小説" );
gameGenreArr.push("サバイバルホラー,ビジュアルノベル" );
gameGenreArr.push("サッカー" );
gameGenreArr.push("推理作品,ミステリー" );
gameGenreArr.push("ホラー映画,ホラー,青年漫画" );
gameGenreArr.push("プラットフォーム・ゲーム,サバイバルホラー,アクションアドベンチャーゲーム" );
gameGenreArr.push("ハックアンドスラッシュ" );
gameGenreArr.push("推理作品" );
gameGenreArr.push("ロボットもの,ビジュアルノベル,少年漫画,アダルトゲーム" );
gameGenreArr.push("アドベンチャーゲーム,アクションアドベンチャーゲーム,アクションゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,list of video games based on anime or manga,ロボットもの" );
gameGenreArr.push("ロボットもの,シミュレーションゲーム" );
gameGenreArr.push("ビジュアルノベル,ロボットもの" );
gameGenreArr.push("コンピュータRPG,ロボットもの" );
gameGenreArr.push("ドラマ" );
gameGenreArr.push("メトロイドヴァニア,アクションゲーム" );
gameGenreArr.push("アドベンチャーゲーム,コメディ,SF漫画,アドベンチャー" );
gameGenreArr.push("ビジュアルノベル,少年漫画,アダルトゲーム" );
gameGenreArr.push("ドラマ,ファンタジー,SF漫画,ハーレム系,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("traditional video game" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,ロボットもの" );
gameGenreArr.push("サードパーソン・シューティングゲーム,ロボットもの" );
gameGenreArr.push("コメディ,ドラマ,恋愛,SF漫画,アドベンチャー,ロボットもの" );
gameGenreArr.push("ドラマ,恋愛,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("ターン制ストラテジー,シミュレーションゲーム,シミュレーションロールプレイングゲーム,turn-based tactics" );
gameGenreArr.push("アクション,少年漫画" );
gameGenreArr.push("ベルトスクロールアクションゲーム,ハックアンドスラッシュ,クロスオーバー作品" );
gameGenreArr.push("2次元コンピュータグラフィックス,ベルトスクロールアクションゲーム" );
gameGenreArr.push("ハックアンドスラッシュ,クロスオーバー作品" );
gameGenreArr.push("コンピュータRPG,シミュレーションゲーム" );
gameGenreArr.push("ハックアンドスラッシュ,アクションゲーム" );
gameGenreArr.push("ブチノメセ！,ハックアンドスラッシュ,ベルトスクロールアクションゲーム" );
gameGenreArr.push("コンピュータRPG,クロスオーバー作品" );
gameGenreArr.push("アクション,アドベンチャー" );
gameGenreArr.push("アクションゲーム,リアルタイムタクティクス" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,SFゲーム" );
gameGenreArr.push("アドベンチャーゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ファンタジー,ビジュアルノベル" );
gameGenreArr.push("対戦格闘ゲーム,ベルトスクロールアクションゲーム,シミュレーションロールプレイングゲーム" );
gameGenreArr.push("ハーレム系,ビジュアルノベル" );
gameGenreArr.push("ビジュアルノベル,アドベンチャーゲーム" );
gameGenreArr.push("city-building game,ストラテジーゲーム" );
gameGenreArr.push("アクションゲーム,魔法少女もの" );
gameGenreArr.push("冒険,ビジュアルノベル" );
gameGenreArr.push("ビジュアルノベル,グラフィックアドベンチャーゲーム" );
gameGenreArr.push("パズルゲーム,アクションゲーム" );
gameGenreArr.push("恋愛,ファンタジー,ビジュアルノベル" );
gameGenreArr.push("乙女ゲーム,冒険,ビジュアルノベル" );
gameGenreArr.push("学園もの,少女漫画" );
gameGenreArr.push("ドラマ,ハーレム系,ロボットもの" );
gameGenreArr.push("コメディ,魔法少女もの,ロボットもの" );
gameGenreArr.push("ship simulator" );
gameGenreArr.push("ミュージカル映画,コメディ,アクション,ファンタジー,コメディ映画" );
gameGenreArr.push("アクションロールプレイングゲーム,コンピュータRPG,クロスオーバー作品" );
gameGenreArr.push("サイバーパンク" );
gameGenreArr.push("学園もの,コメディ" );
gameGenreArr.push("恋愛,ファンタジー,魔法少女もの,ロボットもの" );
gameGenreArr.push("ホラー,魔法少女もの" );
gameGenreArr.push("ドラマ映画" );
gameGenreArr.push("アクションロールプレイングゲーム,SFゲーム" );
gameGenreArr.push("アーケードゲーム,シューティングゲーム" );
gameGenreArr.push("ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("sumo wrestling video game" );
gameGenreArr.push("鉄道シミュレーター" );
gameGenreArr.push("学園もの,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("ドラマ,アクション,やおい,ファンタジー,ビジュアルノベル,少女漫画,青年漫画" );
gameGenreArr.push("アクションゲーム,ビジュアルノベル,ロボットもの,アダルトゲーム" );
gameGenreArr.push("アクション,ファンタジー,アドベンチャー,コメディドラマ" );
gameGenreArr.push("combat" );
gameGenreArr.push("アクション,ファンタジー,ホラー,vampire film" );
gameGenreArr.push("学園もの,恋愛,少年漫画" );
gameGenreArr.push("アダルトゲーム" );
gameGenreArr.push("学園もの,恋愛,ドラマ,ビジュアルノベル,ファンタジー,ハーレム系" );
gameGenreArr.push("音楽ゲーム,リズムゲーム,exergaming" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,アクションロールプレイングゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,サイエンス・フィクション" );
gameGenreArr.push("アクションアドベンチャーゲーム,アクションゲーム,シューティングゲーム,ベルトスクロールアクションゲーム" );
gameGenreArr.push("サイエンス・フィクション,ビジュアルノベル" );
gameGenreArr.push("アクションロールプレイングゲーム,オープンワールド,コンピュータRPG" );
gameGenreArr.push("アクションロールプレイングゲーム,オープンワールド,ファーストパーソン・シューティングゲーム,サードパーソン・シューティングゲーム,コンピュータRPG" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("アクションアドベンチャーゲーム,ファーストパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("ビジュアルノベル,アダルトゲーム,ドラマ,アクション映画,フィクション,ドラマ,ファンタジー" );
gameGenreArr.push("vehicle simulation game" );
gameGenreArr.push("学園もの" );
gameGenreArr.push("パズルゲーム,音楽ゲーム" );
gameGenreArr.push("コメディ,ハーレム系" );
gameGenreArr.push("学園もの,ドラマ,ビジュアルノベル,恋愛,ファンタジー,ハーレム系,アダルトゲーム" );
gameGenreArr.push("ネオ・ノワール,オープンワールド" );
gameGenreArr.push("ドラマ,恋愛,ビジュアルノベル" );
gameGenreArr.push("ドラマ,ビジュアルノベル" );
gameGenreArr.push("恋愛小説,ビジュアルノベル,ドラマ,恋愛" );
gameGenreArr.push("サバイバルゲーム,アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("グラフィックアドベンチャーゲーム,アドベンチャーゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,シミュレーションロールプレイングゲーム,クロスオーバー作品" );
gameGenreArr.push("シミュレーション" );
gameGenreArr.push("プラットフォーム・ゲーム,side-scrolling video game" );
gameGenreArr.push("アクションアドベンチャーゲーム,クロスオーバー作品" );
gameGenreArr.push("格闘技" );
gameGenreArr.push("list of artificial pet games" );
gameGenreArr.push("攻略本" );
gameGenreArr.push("タクティカルシューター,オープンワールド" );
gameGenreArr.push("アクションゲーム,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("恋愛,アクション,アドベンチャー,コメディドラマ" );
gameGenreArr.push("サイエンス・フィクション,スリラー,ビジュアルノベル" );
gameGenreArr.push("学園もの,ドラマ,ビジュアルノベル,恋愛,ファンタジー,青年漫画,少年漫画" );
gameGenreArr.push("音楽ゲーム,rail shooter" );
gameGenreArr.push("SF漫画,ビジュアルノベル,青年漫画,少年漫画,ロボットもの" );
gameGenreArr.push("ビジュアルノベル,学園もの,エッチ,恋愛,ハーレム系,アダルトゲーム" );
gameGenreArr.push("エッチ,恋愛,ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("レースゲーム,スポーツゲーム" );
gameGenreArr.push("ロマンチック・ラブ" );
gameGenreArr.push("SF漫画,ビジュアルノベル" );
gameGenreArr.push("機械翻訳" );
gameGenreArr.push("シミュレーションゲーム,ストラテジーゲーム" );
gameGenreArr.push("コンピュータRPG,オープンワールド,アクションロールプレイングゲーム" );
gameGenreArr.push("コンピュータRPG,オープンワールド,アクションロールプレイングゲーム,ファンタジー,アクションアドベンチャーゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,サバイバルホラー,ステルスゲーム" );
gameGenreArr.push("学園もの,恋愛,日常系,ビジュアルノベル,ハーレム系,アダルトゲーム" );
gameGenreArr.push("学園もの,ドラマ,恋愛,ビジュアルノベル,ハーレム系,アダルトゲーム" );
gameGenreArr.push("プラットフォーム・ゲーム,ファーストパーソン・シューティングゲーム,ステルスゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,リアルタイムストラテジー" );
gameGenreArr.push("コメディ" );
gameGenreArr.push("アクションゲーム,ストラテジーゲーム,リアルタイムタクティクス,タクティカルシューター" );
gameGenreArr.push("コメディ,SF漫画" );
gameGenreArr.push("グラフィックノベル,ビジュアルノベル" );
gameGenreArr.push("ストラテジーゲーム,ロボットもの" );
gameGenreArr.push("ビジュアルノベル,テレビコメディ" );
gameGenreArr.push("スペキュレイティブ・フィクション映画,冒険映画" );
gameGenreArr.push("シミュレーションロールプレイングゲーム,クロスオーバー作品" );
gameGenreArr.push("コメディ,SF漫画,アドベンチャー,ハーレム系" );
gameGenreArr.push("アクション,少女漫画,青年漫画,やおい" );
gameGenreArr.push("対戦格闘ゲーム,冒険" );
gameGenreArr.push("アクションゲーム,ピンボール,クロスオーバー作品" );
gameGenreArr.push("子供番組,テレビコメディ" );
gameGenreArr.push("ベルトスクロールアクションゲーム,ハックアンドスラッシュ" );
gameGenreArr.push("学園もの,ドラマ,アクション,少年漫画" );
gameGenreArr.push("アクションゲーム,対戦格闘ゲーム" );
gameGenreArr.push("パズルゲーム,迷路ゲーム" );
gameGenreArr.push("プラットフォーム・ゲーム,迷路ゲーム" );
gameGenreArr.push("ベルトスクロールアクションゲーム,迷路ゲーム" );
gameGenreArr.push("コンピュータRPG,プラットフォーム・ゲーム" );
gameGenreArr.push("tennis video game" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,ステルスゲーム" );
gameGenreArr.push("カジノゲーム" );
gameGenreArr.push("アクションゲーム,ステルスゲーム,アドベンチャーゲーム" );
gameGenreArr.push("アクションゲーム,プラットフォーム・ゲーム,アドベンチャーゲーム" );
gameGenreArr.push("ドラマ,恋愛,ミステリー,SF漫画,アドベンチャー,ロボットもの" );
gameGenreArr.push("ゲームミュージック" );
gameGenreArr.push("ストラテジーゲーム,ドラマ,青年漫画,長編小説" );
gameGenreArr.push("ファンタジー,アドベンチャー,少年漫画" );
gameGenreArr.push("恋愛,ファンタジー,ビジュアルノベル,少年漫画" );
gameGenreArr.push("ターン制ストラテジー,tactical wargame" );
gameGenreArr.push("アクション" );
gameGenreArr.push("グランドストラテジー,戦争ゲーム,シミュレーションゲーム,ターン制ストラテジー,シミュレーションロールプレイングゲーム" );
gameGenreArr.push("学園もの,ファンタジー,ビジュアルノベル,ハーレム系,魔法少女もの,アダルトゲーム,長編小説" );
gameGenreArr.push("MMORPG,オープンワールド" );
gameGenreArr.push("アドベンチャーゲーム,コメディ,恋愛,ビジュアルノベル,ハーレム系" );
gameGenreArr.push("MMORPG,ハイ・ファンタジー" );
gameGenreArr.push("人生シミュレーションゲーム,オープンワールド" );
gameGenreArr.push("turn-based tactics" );
gameGenreArr.push("アクションロールプレイングゲーム,MMORPG" );
gameGenreArr.push("アクションゲーム,MMOゲーム" );
gameGenreArr.push("タクティカルシューター,サードパーソン・シューティングゲーム,ファーストパーソン・シューティングゲーム,オープンワールド" );
gameGenreArr.push("ビジュアルノベル,青年漫画" );
gameGenreArr.push("リアルタイムタクティクス,ターン制ストラテジー" );
gameGenreArr.push("アダルトゲーム,ビジュアルノベル,学園もの,ドラマ,ファンタジー,ハーレム系,長編小説" );
gameGenreArr.push("ストラテジーゲーム,コメディ,SF漫画,魔法少女もの,少年漫画" );
gameGenreArr.push("ヘンタイ,ファンタジー,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("ミニスケープ,コンピュータゲーム" );
gameGenreArr.push("コンピュータRPG,サードパーソン・シューティングゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,SFゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,戦争ゲーム" );
gameGenreArr.push("ピンボールゲーム" );
gameGenreArr.push("学園もの,ドラマ,恋愛,ファンタジー,ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("ファンタジー,ビジュアルノベル,魔法少女もの,アダルトゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,サードパーソン・シューティングゲーム,コンピュータRPG" );
gameGenreArr.push("vehicle simulation game,サードパーソン・シューティングゲーム" );
gameGenreArr.push("タワーディフェンス,サードパーソン・シューティングゲーム" );
gameGenreArr.push("シューティングゲーム,tank simulation game" );
gameGenreArr.push("プラットフォーム・ゲーム,ダンジョンアドベンチャー,アクションロールプレイングゲーム,コンピュータRPG" );
gameGenreArr.push("学園もの,コメディ,ドラマ" );
gameGenreArr.push("シューティングゲーム,クロスオーバー作品" );
gameGenreArr.push("アクション,ファンタジー,アドベンチャー,魔法少女もの" );
gameGenreArr.push("フォーミュラ1,レースゲーム" );
gameGenreArr.push("アドベンチャー,ロボットもの" );
gameGenreArr.push("スポーツゲーム,golf video game" );
gameGenreArr.push("フォーミュラ1" );
gameGenreArr.push("レースゲーム,シミュレーションゲーム" );
gameGenreArr.push("レースゲーム,アクションゲーム" );
gameGenreArr.push("ビリヤード" );
gameGenreArr.push("children's film,コメディ映画,クライム映画" );
gameGenreArr.push("サードパーソン・シューティングゲーム,サイコロジカルホラー" );
gameGenreArr.push("survival" );
gameGenreArr.push("チェス" );
gameGenreArr.push("アクションロールプレイングゲーム,ハックアンドスラッシュ" );
gameGenreArr.push("ハーレム系" );
gameGenreArr.push("リアルタイムストラテジー,シミュレーションロールプレイングゲーム,アクションロールプレイングゲーム" );
gameGenreArr.push("魔法少女もの" );
gameGenreArr.push("メトロイドヴァニア,プラットフォーム・ゲーム,シューティングゲーム" );
gameGenreArr.push("オープンワールド" );
gameGenreArr.push("サードパーソン・シューティングゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("スポーツゲーム,野球" );
gameGenreArr.push("アドベンチャーゲーム,ホラー,青年漫画,少年漫画" );
gameGenreArr.push("sports manager video game" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,アクションゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ファーストパーソン・シューティングゲーム,ステルスゲーム" );
gameGenreArr.push("リアルタイムストラテジー,コンピュータRPG" );
gameGenreArr.push("グランドストラテジー,リアルタイムストラテジー,ウォー・シミュレーションゲーム,historic game" );
gameGenreArr.push("サバイバルホラー,サードパーソン・シューティングゲーム" );
gameGenreArr.push("submarine simulator" );
gameGenreArr.push("対戦格闘ゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("4X,ターン制ストラテジー,ストラテジーゲーム,シミュレーションゲーム,グランドストラテジー" );
gameGenreArr.push("スポーツ,アイスホッケー" );
gameGenreArr.push("学園もの,ドラマ,恋愛,ビジュアルノベル,少年漫画,アダルトゲーム" );
gameGenreArr.push("スポーツゲーム,経営管理論" );
gameGenreArr.push("アダルトゲーム,ビジュアルノベル,コンピュータRPG" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,サイコロジカルホラー" );
gameGenreArr.push("シミュレーションゲーム,ゴッドゲーム" );
gameGenreArr.push("ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("アダルトゲーム,ビジュアルノベル,青年漫画" );
gameGenreArr.push("美少女ゲーム,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("ミステリー,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("ファンタジー,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("学園もの,エッチ,ファンタジー,ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("人生シミュレーションゲーム,ゴッドゲーム" );
gameGenreArr.push("アクションゲーム,アクション,ビジュアルノベル,青年漫画,少年漫画" );
gameGenreArr.push("シミュレーションゲーム,経営シミュレーションゲーム" );
gameGenreArr.push("シューティングゲーム,インディーズゲーム" );
gameGenreArr.push("スポーツゲーム,ファンタジー" );
gameGenreArr.push("アクションゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,対戦格闘ゲーム,クロスオーバー作品" );
gameGenreArr.push("車両戦闘ゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,車両戦闘ゲーム,オープンワールド" );
gameGenreArr.push("スポーツゲーム,オープンワールド" );
gameGenreArr.push("パズルゲーム,パズル" );
gameGenreArr.push("パズルゲーム,アニメ" );
gameGenreArr.push("アクションアドベンチャーゲーム,オープンワールド,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,オープンワールド,サードパーソン・シューティングゲーム" );
gameGenreArr.push("オープンワールド,レースゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,アドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("タワーディフェンス" );
gameGenreArr.push("endless runner game" );
gameGenreArr.push("パズルゲーム,コンピュータRPG" );
gameGenreArr.push("アドベンチャーゲーム,サイコロジカルホラー" );
gameGenreArr.push("音楽ゲーム,クロスオーバー作品" );
gameGenreArr.push("アクションロールプレイングゲーム,迷路ゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,リアルタイムタクティクス" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,サイエンス・フィクション,アクションゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("アーケードゲーム,迷路ゲーム" );
gameGenreArr.push("アクションゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,オープンワールド,コンピュータRPG" );
gameGenreArr.push("アクションロールプレイングゲーム,ダンジョンアドベンチャー,ハックアンドスラッシュ,コンピュータRPG" );
gameGenreArr.push("リアルタイムストラテジー,ターン制ストラテジー,リアルタイムタクティクス" );
gameGenreArr.push("ミニスケープ,city-building game,MMOゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,バトルロイヤルゲーム" );
gameGenreArr.push("サイコロジカルホラー,サードパーソン・シューティングゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ベルトスクロールアクションゲーム,ステルスゲーム,オープンワールド" );
gameGenreArr.push("サイエンス・フィクション,リアルタイムストラテジー" );
gameGenreArr.push("ステルスゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("ターン制ストラテジー,4X,グランドストラテジー" );
gameGenreArr.push("恋愛,エッチ,ビジュアルノベル,アダルトゲーム" );
gameGenreArr.push("学園もの,アダルトゲーム" );
gameGenreArr.push("プラットフォーム・ゲーム,レベル・エディタ" );
gameGenreArr.push("コンピュータRPG,アドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("アクションアドベンチャーゲーム,パズルゲーム,プラットフォーム・ゲーム" );
gameGenreArr.push("パーティーゲーム,クロスオーバー作品" );
gameGenreArr.push("アクションアドベンチャーゲーム,サイバーパンク,オープンワールド" );
gameGenreArr.push("ドラマ映画,文学を原作とする映画作品" );
gameGenreArr.push("コンピュータRPG,アダルトゲーム,ビジュアルノベル" );
gameGenreArr.push("コンピュータRPG,青年漫画" );
gameGenreArr.push("サードパーソン・シューティングゲーム,アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("J-POP" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,オープンワールド,タクティカルシューター,シミュレーションゲーム" );
gameGenreArr.push("ステルスゲーム,アクションアドベンチャーゲーム,シューティングゲーム" );
gameGenreArr.push("アクション映画,ファンタジー映画" );
gameGenreArr.push("コンピュータRPG,オープンワールド,ターン制ストラテジー" );
gameGenreArr.push("コンピュータゲーム" );
gameGenreArr.push("4X,ターン制ストラテジー" );
gameGenreArr.push("スノーボード,スポーツゲーム" );
gameGenreArr.push("パズルゲーム,アドベンチャーゲーム" );
gameGenreArr.push("アクション,ホラー,青年漫画" );
gameGenreArr.push("対戦格闘ゲーム,サイバーパンク" );
gameGenreArr.push("スポーツゲーム,ビーチバレー" );
gameGenreArr.push("漫画" );
gameGenreArr.push("百合,ビジュアルノベル" );
gameGenreArr.push("ドラマ,ビジュアルノベル,ハーレム系,青年漫画,アダルトゲーム" );
gameGenreArr.push("list of party video games" );
gameGenreArr.push("ファンタジー,少女漫画,ビジュアルノベル,ファンタジー小説" );
gameGenreArr.push("スポーツゲーム,クィディッチ,アクションゲーム" );
gameGenreArr.push("コンピュータRPG,コメディ,アクション,ファンタジー" );
gameGenreArr.push("side-scrolling video game,ベルトスクロールアクションゲーム" );
gameGenreArr.push("ゴッドゲーム,リアルタイムストラテジー" );
gameGenreArr.push("スーパースコープ" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,アクションゲーム,ストラテジーゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,サードパーソン・シューティングゲーム,プラットフォーム・ゲーム" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,SFゲーム,アクションゲーム,サバイバルホラー" );
gameGenreArr.push("ステルスゲーム,ファーストパーソン・シューティングゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("ストラテジーゲーム,ウォー・シミュレーションゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,ステルスゲーム" );
gameGenreArr.push("アクションロールプレイングゲーム,ファーストパーソン・シューティングゲーム" );
gameGenreArr.push("ミニスケープ,リアルタイムストラテジー,経営シミュレーションゲーム" );
gameGenreArr.push("サードパーソン・シューティングゲーム,車両戦闘ゲーム,オープンワールド" );
gameGenreArr.push("scrolling shooter" );
gameGenreArr.push("ファンタジー映画,children's film,コメディ映画" );
gameGenreArr.push("4X,ターン制ストラテジー,グランドストラテジー,ウォー・シミュレーションゲーム,オープンワールド" );
gameGenreArr.push("文学を原作とする映画作品,ファンタジー映画,バディフィルム" );
gameGenreArr.push("コンピュータRPG,アクションロールプレイングゲーム" );
gameGenreArr.push("various genre" );
gameGenreArr.push("スポーツゲーム,アイスホッケー" );
gameGenreArr.push("アクション,ファンタジー,SF漫画" );
gameGenreArr.push("学園もの,SF漫画,スポ根" );
gameGenreArr.push("プラットフォーム・ゲーム,レースゲーム,パーティゲーム" );
gameGenreArr.push("シューティングゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("コンピュータRPG,ベルトスクロールアクションゲーム,対戦格闘ゲーム" );
gameGenreArr.push("アドベンチャーゲーム,教育ゲーム,パーティゲーム,プラットフォーム・ゲーム,パズルゲーム,レースゲーム,コンピュータRPG,スポーツゲーム" );
gameGenreArr.push("シューティングゲーム,サイエンス・フィクション" );
gameGenreArr.push("アクションゲーム,アクションアドベンチャーゲーム,ハックアンドスラッシュ" );
gameGenreArr.push("レースゲーム,アクションアドベンチャーゲーム,オープンワールド" );
gameGenreArr.push("アクションアドベンチャーゲーム,ステルスゲーム,オープンワールド" );
gameGenreArr.push("コンピュータRPG,Eastern role-playing game,たまごっち,アクションロールプレイングゲーム,パズルゲーム" );
gameGenreArr.push("特撮" );
gameGenreArr.push("クロスオーバー作品,コンピュータRPG" );
gameGenreArr.push("ミリタリーSF,ロボットもの" );
gameGenreArr.push("対戦格闘ゲーム,コンピュータRPG" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,兵棋演習,タクティカルシューター" );
gameGenreArr.push("ロールプレイングゲーム,オープンワールド,コンピュータRPG" );
gameGenreArr.push("サバイバルホラー,ステルスゲーム,アクションアドベンチャーゲーム" );
gameGenreArr.push("ミリタリーSF,アニメ" );
gameGenreArr.push("学園もの,ファンタジー小説" );
gameGenreArr.push("対戦格闘ゲーム,弾幕系シューティング" );
gameGenreArr.push("リアルタイムストラテジー,MMORPG,トレーディングカードゲーム" );
gameGenreArr.push("rail shooter,アクションゲーム" );
gameGenreArr.push("スポーツゲーム,sports manager video game,association football video game" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,西部劇" );
gameGenreArr.push("ファーストパーソン・シューティングゲーム,サバイバルホラー,オープンワールド" );
gameGenreArr.push("アドベンチャー,コメディドラマ" );
gameGenreArr.push("turn-based tactics,ターン制ストラテジー" );
gameGenreArr.push("コンピュータRPG,ダンジョンアドベンチャー" );
gameGenreArr.push("アクションアドベンチャーゲーム,コンピュータRPG,迷路ゲーム" );
gameGenreArr.push("シューティングゲーム,アクションゲーム" );
gameGenreArr.push("アクションアドベンチャーゲーム,ファーストパーソン・シューティングゲーム,サードパーソン・シューティングゲーム" );
gameGenreArr.push("アクション映画,ファンタジー映画,コメディ映画,children's film,flashback film" );
gameGenreArr.push("children's film,coming-of-age story,ドラマ映画" );
gameGenreArr.push("バディフィルム,children's film,コメディ映画,ファミリー映画" );
gameGenreArr.push("伝記映画" );
gameGenreArr.push("弾幕系シューティング" );
gameGenreArr.push("ファンタジー映画,children's film" );
